export { About } from './About'
export { Contact } from './Contact'
export { Landing } from './Landing'
export {Login } from './Login'
export { NavBar } from './NavBar'
export { Project } from './Project'
export { Projects } from './Projects'
